import { Appointment, AppointmentStatus } from '@/components/patient-admision/appointment-statistics';
import { format, subDays, addDays } from 'date-fns';

export const mockAppointments: Appointment[] = [
  {
    id: 'mock1',
    nombre: 'Elena',
    apellidos: 'Vargas Llosa',
    fechaConsulta: format(new Date(), 'yyyy-MM-dd'),
    horaConsulta: '09:00',
    motivoConsulta: 'Control Anual',
    estado: 'pendiente',
    notas: 'Paciente refiere sentirse bien, chequeo de rutina.',
    telefono: '555-0101',
    email: 'elena.vargas@example.com',
    duracion: 30,
    costoConsulta: 50,
  },
  {
    id: 'mock2',
    nombre: 'Carlos',
    apellidos: 'Ruiz Zafón',
    fechaConsulta: format(subDays(new Date(), 5), 'yyyy-MM-dd'),
    horaConsulta: '11:30',
    motivoConsulta: 'Dolor de Espalda',
    estado: 'completada',
    notas: 'Se recomienda fisioterapia y analgésicos. Próxima cita en 2 semanas si no mejora.',
    telefono: '555-0202',
    email: 'carlos.ruiz@example.com',
    duracion: 45,
    costoConsulta: 75,
  },
  {
    id: 'mock3',
    nombre: 'Isabel',
    apellidos: 'Allende Llona',
    fechaConsulta: format(addDays(new Date(), 3), 'yyyy-MM-dd'),
    horaConsulta: '15:00',
    motivoConsulta: 'Revisión Postoperatoria',
    estado: 'pendiente',
    notas: 'Revisar cicatrización y evolución general.',
    telefono: '555-0303',
    email: 'isabel.allende@example.com',
    duracion: 30,
  },
  {
    id: 'mock4',
    nombre: 'Gabriel',
    apellidos: 'García Márquez',
    fechaConsulta: format(subDays(new Date(), 10), 'yyyy-MM-dd'),
    horaConsulta: '10:00',
    motivoConsulta: 'Alergia Estacional',
    estado: 'cancelada',
    notas: 'Paciente canceló por viaje inesperado.',
    telefono: '555-0404',
    email: 'gabriel.garcia@example.com',
  },
  {
    id: 'mock5',
    nombre: 'Laura',
    apellidos: 'Esquivel Valdés',
    fechaConsulta: format(new Date(), 'yyyy-MM-dd'),
    horaConsulta: '14:00',
    motivoConsulta: 'Consulta Pediátrica',
    estado: 'presente',
    notas: 'Vacunación pendiente y revisión de crecimiento.',
    telefono: '555-0505',
    email: 'laura.esquivel@example.com',
    costoConsulta: 60,
  },
];
