// Opciones para los formularios de encuesta
export const FORM_OPTIONS = {
  origin: [
    { value: "google", label: "Google" },
    { value: "facebook", label: "Facebook" },
    { value: "instagram", label: "Instagram" },
    { value: "recomendacion", label: "Recomendación" },
    { value: "sitio_web", label: "Sitio Web" },
    { value: "otro", label: "Otro" },
  ],
  location: [
    { value: "cdmx", label: "Ciudad de México" },
    { value: "edomex", label: "Estado de México" },
    { value: "otro", label: "Otro" },
  ],
  cdmxDelegaciones: [
    { value: "alvaro_obregon", label: "Álvaro Obregón" },
    { value: "azcapotzalco", label: "Azcapotzalco" },
    { value: "benito_juarez", label: "Benito Juárez" },
    { value: "coyoacan", label: "Coyoacán" },
    { value: "cuajimalpa", label: "Cuajimalpa" },
    { value: "cuauhtemoc", label: "Cuauhtémoc" },
    { value: "gustavo_a_madero", label: "Gustavo A. Madero" },
    { value: "iztacalco", label: "Iztacalco" },
    { value: "iztapalapa", label: "Iztapalapa" },
    { value: "magdalena_contreras", label: "Magdalena Contreras" },
    { value: "miguel_hidalgo", label: "Miguel Hidalgo" },
    { value: "milpa_alta", label: "Milpa Alta" },
    { value: "tlahuac", label: "Tláhuac" },
    { value: "tlalpan", label: "Tlalpan" },
    { value: "venustiano_carranza", label: "Venustiano Carranza" },
    { value: "xochimilco", label: "Xochimilco" },
  ],
  edomexMunicipios: [
    { value: "atizapan", label: "Atizapán de Zaragoza" },
    { value: "coacalco", label: "Coacalco" },
    { value: "cuautitlan", label: "Cuautitlán" },
    { value: "cuautitlan_izcalli", label: "Cuautitlán Izcalli" },
    { value: "ecatepec", label: "Ecatepec" },
    { value: "huixquilucan", label: "Huixquilucan" },
    { value: "naucalpan", label: "Naucalpan" },
    { value: "nezahualcoyotl", label: "Nezahualcóyotl" },
    { value: "tlalnepantla", label: "Tlalnepantla" },
    { value: "toluca", label: "Toluca" },
    { value: "otro_edomex", label: "Otro municipio" },
  ],
  symptoms: [
    { value: "dolor_abdominal", label: "Dolor en la zona abdominal" },
    { value: "bulto_visible", label: "Bulto o hinchazón visible" },
    { value: "ictericia", label: "Coloración amarillenta (ictericia)" },
    { value: "dificultad_movimiento", label: "Dificultad para moverme" },
    { value: "nauseas_vomitos", label: "Náuseas y/o vómitos" },
    { value: "dolor_despues_comer", label: "Dolor después de comer" },
    { value: "sensacion_pesadez", label: "Sensación de pesadez" },
    { value: "distension_abdominal", label: "Distensión abdominal" },
    { value: "dolor_esfuerzos", label: "Dolor que aumenta con esfuerzos" },
    { value: "fiebre", label: "Fiebre" },
  ],
  duration: [
    { value: "dias", label: "Días" },
    { value: "semanas", label: "Semanas" },
    { value: "meses", label: "Meses" },
    { value: "anios", label: "Años" },
  ],
  severity: [
    { value: "leve", label: "Leve" },
    { value: "moderada", label: "Moderada" },
    { value: "severa", label: "Severa" },
  ],
  painLevels: [
    { value: 0, label: "Sin dolor" },
    { value: 1, label: "Muy leve" },
    { value: 2, label: "Leve" },
    { value: 3, label: "Moderado" },
    { value: 4, label: "Moderado+" },
    { value: 5, label: "Considerable" },
    { value: 6, label: "Intenso" },
    { value: 7, label: "Muy intenso" },
    { value: 8, label: "Extremo" },
    { value: 9, label: "Insoportable" },
    { value: 10, label: "Máximo imaginable" },
  ],
  limitation: [
    { value: "ninguna", label: "No tengo limitaciones" },
    { value: "leve", label: "Leve" },
    { value: "moderada", label: "Moderada" },
    { value: "severa", label: "Severa" },
  ],
  comorbidities: [
    { value: "diabetes", label: "Diabetes" },
    { value: "hipertension", label: "Hipertensión" },
    { value: "obesidad", label: "Obesidad" },
    { value: "cardiopatia", label: "Enfermedad cardíaca" },
    { value: "cancer", label: "Cáncer" },
    { value: "enfermedad_pulmonar", label: "Enfermedad pulmonar" },
    { value: "enfermedad_renal", label: "Enfermedad renal" },
    { value: "ninguna", label: "Ninguna" },
    { value: "otra", label: "Otra" },
  ],
  studies: [
    { value: "ultrasonido", label: "Ultrasonido" },
    { value: "tomografia", label: "Tomografía (TAC)" },
    { value: "resonancia", label: "Resonancia magnética" },
    { value: "radiografia", label: "Radiografía" },
    { value: "endoscopia", label: "Endoscopía" },
    { value: "laboratorio", label: "Análisis de laboratorio" },
    { value: "ninguno", label: "Ninguno" },
  ],
  treatments: [
    { value: "medicamentos", label: "Medicamentos" },
    { value: "fisioterapia", label: "Fisioterapia" },
    { value: "cirugia_previa", label: "Cirugía previa" },
    { value: "alternativo", label: "Tratamiento alternativo" },
    { value: "ninguno", label: "Ninguno" },
  ],
  insurance: [
    { value: "imss", label: "IMSS" },
    { value: "issste", label: "ISSSTE" },
    { value: "seguro_privado", label: "Seguro Privado" },
    { value: "ninguno", label: "Ninguno" },
    { value: "otro", label: "Otro" },
  ],
  privateInsurance: [
    { value: "gnp", label: "GNP" },
    { value: "axa", label: "AXA" },
    { value: "qualitas", label: "QUALITAS" },
    { value: "atlas", label: "ATLAS" },
    { value: "bupa", label: "BUPA" },
    { value: "metlife", label: "METLIFE" },
    { value: "monterrey", label: "SEGUROS MONTERREY" },
    { value: "otro_seguro", label: "Otro" },
  ],
  factors: [
    { value: "seguridad", label: "Seguridad del procedimiento" },
    { value: "experiencia", label: "Experiencia del cirujano" },
    { value: "proceso_rapido", label: "Proceso rápido" },
    { value: "atencion_personalizada", label: "Atención personalizada" },
    { value: "comodidad_instalaciones", label: "Comodidad de instalaciones" },
    { value: "recomendaciones", label: "Recomendaciones positivas" },
    { value: "tecnologia", label: "Tecnología utilizada" },
  ],
  barriers: [
    { value: "miedo_procedimiento", label: "Miedo al procedimiento" },
    { value: "tiempo_recuperacion", label: "Tiempo de recuperación" },
    { value: "ausencia_laboral", label: "Ausencia laboral" },
    { value: "falta_apoyo", label: "Falta de apoyo familiar" },
    { value: "dudas_necesidad", label: "Dudas sobre necesidad real" },
    { value: "experiencias_negativas", label: "Experiencias negativas previas" },
    { value: "informacion_insuficiente", label: "Información insuficiente" },
  ],
  availability: [
    { value: "inmediata", label: "Inmediata" },
    { value: "1_semana", label: "1 semana" },
    { value: "2_semanas", label: "2 semanas" },
    { value: "1_mes", label: "1 mes" },
    { value: "flexible", label: "Flexible" },
  ],
  decisionTimeline: [
    { value: "inmediato", label: "Inmediato" },
    { value: "dias", label: "Días" },
    { value: "semanas", label: "Semanas" },
    { value: "meses", label: "Meses" },
    { value: "indeciso", label: "Aún indeciso" },
  ],
  timeframes: [
    { value: "urgente", label: "Urgente" },
    { value: "30_dias", label: "30 días" },
    { value: "90_dias", label: "90 días" },
    { value: "sin_prisa", label: "Sin prisa" },
  ],
  supportPerson: [
    { value: "esposo", label: "Esposo/a" },
    { value: "hijos", label: "Hijos" },
    { value: "mama", label: "Mamá" },
    { value: "papa", label: "Papá" },
    { value: "hermanos", label: "Hermanos" },
    { value: "amigos", label: "Amigos" },
    { value: "otro_familiar", label: "Otro familiar" },
    { value: "ninguno", label: "Ninguno" },
  ],
}

// Generar un ID único para la encuesta
export function generateSurveyId(): string {
  return `SV-${Math.random().toString(36).substring(2, 10).toUpperCase()}`
}

// Generate a survey link
export function generateSurveyLink(patientId: number, surveyId: string): string {
  // Generate a link to the standalone survey page
  return `${window.location.origin}/survey/${surveyId}?patientId=${patientId}`
}
